config/routes.rb
Rails.application.routes.draw do

  root 'page#welcome'
  get '/about' => 'page#about'
  get '/get_bing_images' => 'page#get_bing_images'
  
  namespace :admin do
    root 'home#index'
    resources :users
    resources :roles
  end
  resources :issues
  resources :comments, only: [:create]
  get "signup" => "users#signup", :as => "signup"
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"
  resources :users, only: [:create]

end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :comments	
  belongs_to :user
end	

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  def show
     @issue = Issue.find(params[:id])
     @comments = @issue.comments
  end

  def new
    if not current_user
        flash[:notice] = "没有执行此操作的权限，请先登录"
        redirect_to :root
        return
      else
        @issue = current_user.issues.build
      end
  end

  def create
   Issue.create(issue_params)
   redirect_to :root
  end

  def edit
    @issue = Issue.find(params[:id])
  end

  def update
    i = Issue.find(params[:id])
    i.update_attributes(issue_params)
    redirect_to :root
  end

  def destroy
    issue = Issue.find(params[:id])
    issue.destroy
    redirect_to :root
  end

  private
    def issue_params
      params.require(:issue).permit(:title,:content,:user_id)	
    end
end

app/views/issues/_form.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for @issue do |f| %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <!--hidden field-->
      <%=f.hidden_field :user_id %>
      <p><%= f.submit  :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/edit.html.erb
<%= render "form"%>

app/views/issues/new.html.erb
<%= render "form"%>

app/views/issues/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @issue.title %>
    <% if current_user && current_user == @issue.user %>
       <%= link_to 'Destroy', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
       <%= link_to 'edit', edit_issue_path(@issue), class: "btn btn-primary" %>
     <% end %>
  </div>
</div>
<div class="container">
  <div class="replies">
    <article class="reply clearfix">
      <div class="avatar">
        <%= image_tag @issue.user.avatar, class: "image-circle" %>
      </div>
      <div class="body">
        <div class="heading">
          <h5 class="name"><%= link_to @issue.user.name, "#" %></h5>
        </div>
        <%= markdown(@issue.content)%>
      </div>
    </article>
    <% @comments.each do |c| %>
      <%= render partial: 'shared/comment', locals: {c: c} %>
    <% end %>
  </div>
   <% if current_user %>
     <%= render partial: 'shared/comment_box', locals: {issue: @issue} %>
   <% else %>
     <%= link_to "登录发评论", login_path %>
   <% end %>
</div>