config/routes.rb
Rails.application.routes.draw do

  root 'page#welcome'
  get '/about' => 'page#about'
  get '/get_bing_images' => 'page#get_bing_images'
  
  namespace :admin do
    root 'home#index'
    resources :users
    resources :roles
  end
  resources :issues
  resources :comments, only: [:create]
  get "signup" => "users#signup", :as => "signup"
  get "login" => "users#login", :as => "login"
  post "create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"
  resources :users, only: [:create]

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :user_roles, :dependent => :destroy
  has_many :users, through: :user_roles
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::HghlandController
  def index
    @roles = Role.page(params[:page]).per(10)
  end

  def new

  end

  def create
    @role = Role.new(role_params)
    if @role.save
      flash_msg(:success,"#{params[:commit]}成功")
      redirect_to admin_roles_path
    else
      flash_msg(:error,"#{params[:commit]}失败#{@role.error_msg}")
      render :new
    end
  end

  def edit

  end

  def update
    if @role.update_attributes(role_params)
      flash_msg(:success,"#{params[:commit]}成功")
      redirect_to admin_roles_path
    else
      flash_msg(:error,"#{params[:commit]}失败#{@role.error_msg}")
      render :edit
    end
  end

  def destroy
    @role.destroy ? flash_msg(:success,"已成功删除") :  flash_msg(:error,"删除失败#{@role.error_msg}")
    redirect_to params[:back]
  end

  private
  def role_params
    params.require(:role).permit(:name, :desc)
  end
end

app/views/admin/roles/_form.html.erb
<%= simple_form_for [:admin, @role] do |f| %>
  <section class="content">

    <!-- SELECT2 EXAMPLE -->
    <div class="box box-default">
      <!-- /.box-header -->
      <div class="box-body">
        <div class="row">
          <div class="col-md-6">
            <div class="form-group">
              <label>名称：</label>
              <%=  f.text_field :name, class: "form-control" %>
            </div>

            <div class="form-group">
              <label>描述：</label>
              <%= f.text_area :desc, class: "form-control " %>
            </div>
          </div>
        </div>
        <!-- /.row -->
      </div>
      <%= render "/admin/shared/form_buttons",f: f %>
      <!-- /.box-body -->
    </div>
    <!-- /.box -->
  </section>
<% end %>

app/views/admin/roles/edit.html.erb
<%= legend_name("编辑角色")%>
<%= render "form"%>

app/views/admin/roles/index.html.erb
<%= legend_name("角色管理")%>
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">角色列表</h3>
          <!-- /.box-header -->
          <div class="box-body">
            <%= link_to "新增角色", new_admin_role_path(back: request.fullpath) ,class: "btn btn-primary" %>
            <table class="table table-bordered table-striped dataTable mt10">
              <thead>
              <tr>
                <th>序号</th>
                <th>ID</th>
                <th>名称</th>
                <th>描述</th>
                <th>用户数</th>
                <th>操作</th>
              </tr>
              </thead>
              <tbody>
              <% @roles.each_with_index do |role,index| %>
                <tr>
                  <td><%= index+ 1 %></td>
                  <td><%= role.id %></td>
                  <td><%= role.name %></td>
                  <td><%= role.desc %></td>
                  <td><%= role.users.count %></td>
                  <td class="w120">
                    <div class="btn-group">
                      <button type="button" class="btn btn-info">操作</button>
                      <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <span class="caret"></span>
                        <span class="sr-only">Toggle Dropdown</span>
                      </button>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "修改",edit_admin_role_path(role,back: request.fullpath)%></li>
                        <li><%= link_to "删除",admin_role_path(role,back: request.fullpath) , :method => :delete, data: { confirm: '确定要刪除吗?' } %></li>
                      </ul>
                    </div>
                  </td>
                </tr>
              <% end %>
              </tbody>
            </table>
            <%= paginate @roles %>
          </div>
          <!-- /.box-body -->
        </div>
        <!-- /.box -->
      </div>
    </div>
</section>

app/views/admin/roles/new.html.erb
<%= legend_name("新建角色")%>
<%= render "form"%>